# bisenet v1
cfg = dict(
    model_type='bisenetv1',
    num_aux_heads=2,
    lr_start=1e-2,
    weight_decay=5e-4,
    warmup_iters=1000,
    max_iter=1600,
    im_root='./datasets/Rexroth',
    #im_root='/home/rrh4fe/PycharmProjects/Bilateral-Networks/datasets/Rexroth',
    train_im_anns='./datasets/Rexroth/train.txt',
    #train_im_anns='/home/rrh4fe/PycharmProjects/Bilateral-Networks/datasets/Rexroth/train.txt',
    val_im_anns='./datasets/Rexroth/eval.txt',
    scales=[0.75, 1.,],
    cropsize=[640, 480],
    ims_per_gpu=8,
    use_fp16=True,
    use_sync_bn=False,
    respth='./res',
    categories=2,
    )